/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Interfaz.PaginaPrincipal;
import courier.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mac
 */
public class PaginaInicial extends javax.swing.JFrame {
    
    
    Autoservicio usuario = new Autoservicio();
    PaginaPrincipal ventanaprincipal = new PaginaPrincipal(this,usuario);
    Administracion estadisticas = new Administracion();
    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
        setLocationRelativeTo (null);
        setResizable (false);
        setTitle ("Página Inicial");
    }
    
    static String TipoEstructuraP ,TipoEstructuraNP , TipoEstructuraSeguridad ;
    static String TotalPerecedera, TotalNoPerecedero;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jComboBoxVentanillaEntregaP = new javax.swing.JComboBox<>();
        jComboBoxVentanillaEntregaNP = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxVentanillaSeguridad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonHeapEntrega = new javax.swing.JRadioButton();
        jRadioButtonColaEntrega = new javax.swing.JRadioButton();
        jRadioButtonColaSeguridad = new javax.swing.JRadioButton();
        jRadioButtonHeapSeguridad = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtCantidadPerecederos = new javax.swing.JTextField();
        jtCantidadNP = new javax.swing.JTextField();

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ventanilas de Entregra:");

        jComboBoxVentanillaEntregaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBoxVentanillaEntregaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVentanillaEntregaPActionPerformed(evt);
            }
        });

        jComboBoxVentanillaEntregaNP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBoxVentanillaEntregaNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVentanillaEntregaNPActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 114, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajustes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ventanilas de Entregra:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 98, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ventanilas de Seguridad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, -1, -1));

        jComboBoxVentanillaSeguridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jPanel1.add(jComboBoxVentanillaSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 228, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de estructura:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 103, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de estructura:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 231, -1, -1));

        jRadioButtonHeapEntrega.setBackground(new java.awt.Color(31, 114, 87));
        jRadioButtonHeapEntrega.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonHeapEntrega.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonHeapEntrega.setText("Heap");
        jRadioButtonHeapEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHeapEntregaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonHeapEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 103, -1, -1));

        jRadioButtonColaEntrega.setBackground(new java.awt.Color(31, 114, 87));
        jRadioButtonColaEntrega.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonColaEntrega.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonColaEntrega.setText("Cola");
        jRadioButtonColaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonColaEntregaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonColaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 103, -1, -1));

        jRadioButtonColaSeguridad.setBackground(new java.awt.Color(31, 114, 87));
        jRadioButtonColaSeguridad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonColaSeguridad.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonColaSeguridad.setText("Cola");
        jRadioButtonColaSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonColaSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonColaSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 227, -1, -1));

        jRadioButtonHeapSeguridad.setBackground(new java.awt.Color(31, 114, 87));
        jRadioButtonHeapSeguridad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonHeapSeguridad.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonHeapSeguridad.setText("Heap");
        jRadioButtonHeapSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHeapSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonHeapSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 227, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 296, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, 678, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ventanilas de Entregra P:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 136, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ventanilas de Entregra NP:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 169, -1, -1));
        jPanel1.add(jtCantidadPerecederos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, -1));
        jPanel1.add(jtCantidadNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonHeapEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHeapEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHeapEntregaActionPerformed

    private void jRadioButtonColaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonColaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonColaEntregaActionPerformed

    private void jRadioButtonColaSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonColaSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonColaSeguridadActionPerformed

    private void jRadioButtonHeapSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHeapSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHeapSeguridadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // PARA GENERAR INFO DE ESTADISTICAS
        
        // para definir que tipo de estructira usan las ventanillas de entrega
        if (jRadioButtonHeapEntrega.isSelected()){
            TipoEstructuraP = "HEAP";
            TipoEstructuraNP = "HEAP";
        }
        else if (jRadioButtonColaEntrega.isSelected()){
             TipoEstructuraP = "Cola de Prioridad";
            TipoEstructuraNP = "Cola de Prioridad";
        }
        //para definir que tipo de estructura usan las  ventanillas de seguridad
        if (jRadioButtonHeapSeguridad.isSelected()){
            TipoEstructuraSeguridad = "HEAP";
        }
        else if (jRadioButtonColaSeguridad.isSelected()){
             TipoEstructuraSeguridad = "Cola de Prioridad";
        }

        //para definir la cantidad de ventanillas por tipo de entrega
        TotalPerecedera =  jtCantidadPerecederos.getText();
        TotalNoPerecedero =  jtCantidadPerecederos.getText();
        
        PaginaPrincipal miventanilla = new PaginaPrincipal(Integer.parseInt(jtCantidadPerecederos.getText()), Integer.parseInt(jtCantidadNP.getText()));
        miventanilla.setVisible(true);
        

        estadisticas.datosAdministracion(TipoEstructuraP, TipoEstructuraNP, TipoEstructuraSeguridad, TotalPerecedera, TotalNoPerecedero);

        
        this.setVisible(false);
                JOptionPane.showMessageDialog(new JFrame(),"El TOTAL de ventanillas es de: " + TotalPerecedera + "\n"
                +"El tipo de estructura es " +TipoEstructuraP+ "\n"
                + "El tipo de estructura de seguridad es:" +TipoEstructuraSeguridad, "Datos de Productos Perecederos",JOptionPane.INFORMATION_MESSAGE);
                
                JOptionPane.showMessageDialog(new JFrame(),"El TOTAL de ventanilas es de: " + TotalNoPerecedero + "\n"
               + "El tipo de estructura es " +TipoEstructuraNP + "\n"
                + "El tipo de estructura de seguridad es: " +TipoEstructuraSeguridad, "Datos de Productos NO Perecederos",JOptionPane.INFORMATION_MESSAGE);
   
        //this.jtxtTelefono.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxVentanillaEntregaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVentanillaEntregaPActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxVentanillaEntregaPActionPerformed

    private void jComboBoxVentanillaEntregaNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVentanillaEntregaNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVentanillaEntregaNPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxVentanillaEntregaNP;
    private javax.swing.JComboBox<String> jComboBoxVentanillaEntregaP;
    private javax.swing.JComboBox<String> jComboBoxVentanillaSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonColaEntrega;
    private javax.swing.JRadioButton jRadioButtonColaSeguridad;
    private javax.swing.JRadioButton jRadioButtonHeapEntrega;
    private javax.swing.JRadioButton jRadioButtonHeapSeguridad;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtCantidadNP;
    private javax.swing.JTextField jtCantidadPerecederos;
    // End of variables declaration//GEN-END:variables
}
